### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by ScythianBeastie** [kosch104/CS2-AssetNamePacks#2]
Thank you for putting this together! I am very excited about getting to have better street names auto-applied in my cities! :)

However, I can't get it to work. :(

There's not a lot of documentation, so it's possible that I'm doing things wrong and I just don't know that I am.

I've got about 3,000 names in my (copied in from Klyte's mod for Cities:Skylines I). Is that too many?

I've installed your mod via Thunderstore. 

With Thunderstore, BepInEx is put in a folder that isn't the game main folder (C:\Users\[my username]\AppData\Roaming\Thunderstore Mod Manager\DataFolder\CitiesSkylines2\profiles\Default\BepInEx). 

Your mod goes into the plugins subfolder of that path (full path is C;\Users\[my username]\AppData\Roaming\Thunderstore Mod Manager\DataFolder\CitiesSkylines2\profiles\Default\BepInEx\plugins\Konsi-Asset_Name_Packs).

Under that path, there is apparently supposed to be a "packs/Default" subfolder, but it isn't there; your example file STREET_NAME.en-US.txt.rename is present in the "Konsi-Asset_Name_Packs" folder.

1. Is "Konsi-Asset_Name_Packs" where I should save my STREET_NAME.en-US.txt file?
2. Is STREET_NAME.en-US.txt even the proper name for the file?
3. Can people be renamed with this mod, or is it just streets for now?

Thank you very much for any guidance that you can provide! :)

**Comment by ScythianBeastie** [comment]
UPDATE: I think Thunderstore is not installing the mod properly. It seems to be flattening the internal folder structure.

C:\Users\[my username]\AppData\Roaming\Thunderstore Mod Manager\DataFolder\CitiesSkylines2\profiles\Default\BepInEx**\plugins\Konsi-Asset_Name_Packs**

vs. the path that I saw when I manually installed the mod according to the instructions here on GitHub:

C:\Program Files (x86)\Steam\steamapps\common\Cities Skylines II\BepInEx**\plugins\AssetNamePacks\packs\Default**

Also, this error keeps showing up in the BepInEx CLI window:

![image](https://github.com/kosch104/CS2-AssetNamePacks/assets/39598179/ab165ba2-f83e-45f2-8a67-58a128450fe6)

**Comment by saulsc** [comment]
I just saw that there's another fork of this mod on GitHub. I'm using the one on Thunderstore. But I will try manually installing the other fork and see if I can get it to work.

**Comment by ScythianBeastie** [comment]
I just noticed that there's another branch of this mod (I've been using Default, which is the one on Thunderstore, but the other branch has far better documentation).

Default, the branch I've used: https://github.com/kosch104/CS2-AssetNamePacks
Origin/Main, the better documented branch: https://github.com/kosch104/CS2-AssetNamePacks/tree/origin/main

I'm going to try removing the Thunderstore edition and manually installing the Origin/Main branch, and I'll see if I can get that one to work. I've had no luck with the default branch so far.

UPDATE: I can't seem to download files for that branch unless I want to go file-by-file, which I can't really do at the moment.

**Comment by Mimonsi** [comment]
I am sorry for answering only now, my github notifications didn´t tell me there was activity here. You are correct, I messed up the branches somehow and you found the correct one with more detailed instructions.

To answer the questions of your first post:

1. In your plugins folder there should be one folder of this mod, the name might be slightly off in the documentation. Normally there should be a packs/Default folder in the same folder where the DLL is located, but if not, you can try to create it yourself. 
2. Yes, STREET_NAME.en-US.txt is the proper name if you want to replace STREET_NAME assets in the english language.
3. Yes, people can be renamed, an example can be found in the (now updated) instructions. 

Please note, the Thunderstore edition has the same code as origin/main, only documentation was updated later.

After reading your issue again I noticed that you are probably right with the issues of folder structure, please give me some time to adresss this issue.

**Comment by Mimonsi** [comment]
I now uploaded Version 1.1.0. This should adress all your issues and create an example asset pack on first launch. Please feel free to share your feedback, if you have any. Thank you for your detailed report and findings, it really helped when solving this matter!
